[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "local_ai_server"
version = "0.1.0"
description = "Local AI server with OpenAI-compatible endpoints"
requires-python = ">=3.8"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dynamic = ["dependencies"]

[project.scripts]
local-ai-server = "local_ai_server.__main__:main"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
